### ISSUE TITLE
Check possible vulnerabilities in deps

### ISSUE THREAD

**Issue by gabmontes** [autonomoussoftware/metronome.io#135]

**Comment by pablen** [comment]
Fixed in https://github.com/autonomoussoftware/metronome.io/commit/06da62c2969c2d96b06172321c8e5fe0159efbf4.

There is a remaining vulnerability warning that cannot be addressed right now, but is not that critical in our use case as it is related to potential source code sniffing while developing using Hot Module Replacement, but our code is already open source.

Info on the vulnerability:
https://www.npmjs.com/advisories/725

To fix this we would need to update to `create-react-app`/`react-scripts` > 2.0.0 which is a breaking update and [is not compatible with `react-app-rewired`](https://github.com/timarney/react-app-rewired/issues/162#issuecomment-417872507), required by this project.

**Comment by abenhamdine** [comment]
Actually, react-app-rewired is still compatible with cra 2.1.1, it's just that it's no more maintained.

**Comment by pablen** [comment]
Thanks for the clarification @abenhamdine!
Unfortunately, our current configuration doesn't seem to play well with CRA v2. I'll need to investigate further.
