### ISSUE TITLE
Auction/Dashboard Price in USD Reflection

### ISSUE THREAD

**Issue by Dareknotderek** [autonomoussoftware/metronome.io#165]
@pablen 

A community member mentioned that their iOS devices (iPad, so forth) was incorrectly displaying auction price. Price in ETH is correct, but price in USD is oddly high. Guess is this is a browser related issue for Safari, considering said iOS devices.

**Comment by pablen** [comment]
Current site uses a deprecated version of the Coincap API for fetching ETH prices, which no longer works. So at this point the USD price is unreliable because it will be calculated using the last value cached by the browser.

New site version (hopefully to be release in short) uses a newer version of the Coincap API and thus  USD prices will be correct.
